version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laracollab-app
    ports:
      - "8085:80"
    environment:
      - DB_HOST=mysql-db
      - DB_DATABASE=laracollab_db
      - DB_USERNAME=admin
      - DB_PASSWORD=jfisilvicultura@2026
    networks:
      - laracollab-net
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    container_name: mysql-db
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=jfisilvicultura@2026
      - MYSQL_DATABASE=laracollab_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=jfisilvicultura@2026
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - laracollab-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-pjfisilvicultura@2026"]
      retries: 5
      interval: 10s
      timeout: 5s

networks:
  laracollab-net:
    driver: bridge

volumes:
  mysql-data:
    driver: local